name: GitHub Actions Demo
run-name: ${{ github.actor }} has kicked off a Terraform build
on: [push]
jobs:
  Terraform Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Your Build Started and ran."
